[package]
name = "rnes"
version = "0.1.0"
authors = ["Naymoll <xdarkknight122x@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "^1.0"
bitflags = "^1.3"
enum_dispatch = "0.3.8"